import WrightTools as wt

results = wt.Collection(name='results')
results.create_data(name='neat')
results.create_data(name='messy')
results.create_data(name='confusing')
calibration = results.create_collection(name='calibration')
calibration.create_data(name='OPA1_tune_test')
calibration.create_data(name='OPA2_tune_test')
displays= results.create_collection(name='displays')
displays.create_data(name='figure1')
displayfig2 = displays.create_collection(name='figure2')
displayfig2.create_data(name='main')
displayfig2.create_data(name='inset')

wt.Collection.convert(results,units='eV')

print(isinstance(results.neat.units(), 'eV'))
print(isinstance(results.messy.units(), 'eV'))
print(isinstance(results.confusing.units(), 'eV'))
print(isinstance(results.calibration.units(), 'eV'))
print(isinstance(results.calibration.OPA1_tune_test.units(), 'eV'))
print(isinstance(results.calibration.OPA2_tune_test.units(), 'eV'))
print(isinstance(results.displays.units(), 'eV'))
print(isinstance(results.displays.figure1.units(), 'eV'))
print(isinstance(results.displays.displayfig2.units(), 'eV'))
print(isinstance(results.displays.displayfig2.main.units(), 'eV'))
print(isinstance(results.displays.displayfig2.inset.units(), 'eV'))
