version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

formats:
  - epub
  - pdf
